import type { Metadata } from "next";

import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="md:block hidden">
          <Providers>{children}</Providers>
          <Toaster />
        </div>
        <div className="md:hidden w-full h-screen flex justify-center items-center">
          The application does not function on mobile platforms.
        </div>
      </body>
    </html>
  );
}
